// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: logging.h
#pragma once
#include <Arduino.h>

void loggingInit();
void logMsg(const String& s);
String logDump();
