// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: pins.h
#pragma once
#include <Arduino.h>

// Реле → ПЧ SKI780 (low-valid: замыкаем DI на GND)
#define PIN_RELAY_RUN  23   // DI1 = RUN
#define PIN_RELAY_MS3  22   // DI2 = MR3
#define PIN_RELAY_MS2  19   // DI4 = MR2
#define PIN_RELAY_MS1  21   // DI5 = MR1

// Логика реле: активный уровень LOW (на 5В-модулях с опторазвязкой часто так)
#define RELAY_ACTIVE_LOW 1

// Датчики
#define PIN_ONEWIRE      26  // DS18B20 шина
#define PIN_MAX6675_SO   33
#define PIN_MAX6675_CS   25
#define PIN_MAX6675_SCK  27
