// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: profiles.h
#pragma once
#include <Arduino.h>

enum : uint8_t {
  MODE_OFF=0, MODE_MANUAL=1, MODE_IGNITION=2, MODE_HEAT=3, MODE_HOLD=4, MODE_PILOT=5, MODE_ALARM=6
};

struct ModeProfile {
  float T_set, T_hyst;
  float Kp, Ki;
  float Tflue_low, Tflue_high;

  float    auger_steps[4];
  uint16_t auger_ton[4];
  uint16_t auger_off_min, auger_off_max;
  float    auger_off_base, auger_alpha;
  float    auger_ramp_sec, ramp_safety;

  float V1_min, V1_max, V1_ramp_sec;
  float V2_min, V2_base, V2_max, V2_ramp_sec;

  uint32_t ignition_time_ms, cool_time_ms;

  // UI-configurable helpers (per-mode manual fuel/air presets)
  float air_primary_pct_ui;
  float air_secondary_pct_ui;
  float ton_ui_sec;
  float toff_ui_sec;
};

struct CommonSettings {
  uint16_t aug_min_ton_ms;
  uint16_t aug_min_toff_ms;
  float    T_supply_max;
  float    fan_steps[10];
  float    auger_steps10[10];
  float    q100_kgph;
  float    k_material;
};
extern CommonSettings g_common;
extern ModeProfile g_cfg;
extern uint8_t     g_boilerMode;

const char* modeRu(uint8_t m);

// профили по режимам
const ModeProfile& profileOf(uint8_t m);
void updateProfile(uint8_t m, const ModeProfile& p);
void applyProfileToCfg(uint8_t m);
void profilesInit();

// NVS
bool profilesLoadFromNVS();
void profilesSaveToNVS();
void profileFactoryReset(uint8_t m); // вернуть дефолт для одного режима


void commonInit();
void commonSaveToNVS();
bool commonLoadFromNVS();
void commonFactoryReset();
