// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: sensors.h
#pragma once
#include <Arduino.h>

void sensorsInit();
void sensorsTick();

// геттеры температур (NaN если нет)
float getTsupply();   // DS18B20 #0
float getTreturn();   // DS18B20 #1
float getTflue();     // MAX6675
