// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: vfd.h
#pragma once
#include <Arduino.h>
#include "pins.h"

extern volatile uint8_t g_speed_mode;     // 0..8
extern uint32_t         g_lastSpeedChangeMs;

void vfdInit();
void applySpeed(uint8_t sp);              // 0=STOP, 1..8 -> PC-00..07
void setPresetBits(uint8_t idx);          // 0..7

// реле-состояния
inline void setRelay(uint8_t pin, bool on){
  if (RELAY_ACTIVE_LOW) digitalWrite(pin, on?LOW:HIGH);
  else                  digitalWrite(pin, on?HIGH:LOW);
}
inline bool relayIsOn(uint8_t pin){
  return RELAY_ACTIVE_LOW ? (digitalRead(pin)==LOW) : (digitalRead(pin)==HIGH);
}
