// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: web.h
#pragma once
#include <Arduino.h>
#include <WebServer.h>

extern WebServer server;

void webInit();
void webTick();
