// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: BoilerControl_ESP32.ino
/*
  BoilerControl ESP32 — v10
  Плата: ESP32 Dev Module
  Пины реле (SKI780, low-valid): RUN=23, MS3=22, MS2=19, MS1=21
  Датчики: DS18B20=26; MAX6675 SCK=27, CS=25, SO=33
*/

#include <Arduino.h>
#include <WiFi.h>
#include "pins.h"
#include "logging.h"
#include "profiles.h"
#include "vfd.h"
#include "sensors.h"
#include "control.h"
#include "web.h"

#define USE_AP_MODE 1
const char* AP_SSID = "BoilerESP32";
const char* AP_PASS = "12345678";

static void setupWiFi(){
  #if USE_AP_MODE
    WiFi.mode(WIFI_AP);
    WiFi.softAP(AP_SSID, AP_PASS);
    logMsg(String("WiFi AP: ")+AP_SSID+" IP="+WiFi.softAPIP().toString());
  #else
    WiFi.mode(WIFI_STA);
    WiFi.begin("",""); // <- вставь SSID/PASS
    uint32_t t0=millis();
    while(WiFi.status()!=WL_CONNECTED && millis()-t0<15000){ delay(250); }
    logMsg(String("WiFi STA: ")+WiFi.localIP().toString());
  #endif
}

void setupPins(){
  pinMode(PIN_RELAY_RUN, OUTPUT);
  pinMode(PIN_RELAY_MS1, OUTPUT);
  pinMode(PIN_RELAY_MS2, OUTPUT);
  pinMode(PIN_RELAY_MS3, OUTPUT);
  // безопасное выключенное состояние
  if (RELAY_ACTIVE_LOW){
    digitalWrite(PIN_RELAY_RUN, HIGH);
    digitalWrite(PIN_RELAY_MS1, HIGH);
    digitalWrite(PIN_RELAY_MS2, HIGH);
    digitalWrite(PIN_RELAY_MS3, HIGH);
  }else{
    digitalWrite(PIN_RELAY_RUN, LOW);
    digitalWrite(PIN_RELAY_MS1, LOW);
    digitalWrite(PIN_RELAY_MS2, LOW);
    digitalWrite(PIN_RELAY_MS3, LOW);
  }
}

void relaySelfTest(){
  logMsg("Самотест реле");
  setRelay(PIN_RELAY_RUN, true);  delay(160); setRelay(PIN_RELAY_RUN, false);  delay(120);
  setRelay(PIN_RELAY_MS1, true);  delay(160); setRelay(PIN_RELAY_MS1, false); delay(120);
  setRelay(PIN_RELAY_MS2, true);  delay(160); setRelay(PIN_RELAY_MS2, false); delay(120);
  setRelay(PIN_RELAY_MS3, true);  delay(160); setRelay(PIN_RELAY_MS3, false); delay(120);
}

void setup(){
  Serial.begin(115200); delay(200);
  setupPins();
  setupWiFi();
  loggingInit();
  sensorsInit();         // DS18B20 + MAX6675
  profilesInit();        // дефолтные профили → g_cfg
  vfdInit();             // скорость=STOP
  relaySelfTest();
  controlInit();         // применим профиль текущего режима
  webInit();             // HTTP сервер/маршруты
  logMsg("Старт v10");
}

void loop(){
  webTick();             // server.handleClient()
  sensorsTick();         // опрос датчиков
  controlTick();         // автоматика
}
