// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: logging.cpp
#include "logging.h"

static String buf[240];
static uint8_t head=0;

void loggingInit(){ for(auto &s:buf) s=""; head=0; }

void logMsg(const String& s){
  buf[head]=s;
  head=(head+1)%240;
  Serial.println(s);
}

String logDump(){
  String out;
  for(uint8_t i=0;i<240;i++){
    uint8_t k=(head+i)%240;
    if(buf[k].length()){ out+=buf[k]; out+="\r\n"; }
  }
  return out.length()?out:String("logs empty");
}
