// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: profiles.cpp
#include "profiles.h"
#include "logging.h"
#include <Preferences.h>

ModeProfile g_cfg;
uint8_t     g_boilerMode = MODE_OFF;

static ModeProfile s_defaults[6] = {
  /* OFF */  {60,2,0.06,0.003,150,200,{0.30,0.45,0.60,0.80},{5,6,7,8},4,40,30,0.8,2,1,25,60,2,20,30,65,2,300000,180000},
  /* MAN */  {60,2,0.06,0.003,150,200,{0.30,0.45,0.60,0.80},{5,6,7,8},4,40,30,0.8,2,1,25,60,2,20,30,65,2,300000,180000},
  /* IGN */  {60,2,0.06,0.003,150,200,{0.30,0.45,0.60,0.80},{6,7,8,9},4,40,30,0.8,2,1,28,60,2,22,32,65,2,300000,180000},
  /* HEAT */ {60,2,0.07,0.0035,150,200,{0.30,0.45,0.60,0.80},{6,7,8,9},4,40,28,0.85,2,1,25,60,2,20,30,65,2,300000,180000},
  /* HOLD */ {60,2,0.06,0.003,150,200,{0.30,0.45,0.60,0.80},{5,6,7,8},4,40,30,0.8,2,1,25,55,2,20,30,60,2,300000,180000},
  /* COOL */ {55,2,0.05,0.002,150,200,{0.30,0.45,0.60,0.80},{4,5,6,7},4,40,32,0.7,2,1,20,40,2,18,25,45,2,300000,180000}
};
static ModeProfile s_profiles[6];

const ModeProfile& profileOf(uint8_t m){ if(m>5)m=5; return s_profiles[m]; }
void updateProfile(uint8_t m, const ModeProfile& p){ if(m>5)m=5; s_profiles[m]=p; }
void applyProfileToCfg(uint8_t m){ if(m>5)m=5; g_cfg = s_profiles[m]; }

const char* modeRu(uint8_t m){
  switch(m){
    case MODE_OFF: return "Выключен";
    case MODE_MANUAL: return "Ручной";
    case MODE_IGNITION: return "Розжиг";
    case MODE_HEAT: return "Нагрев";
    case MODE_HOLD: return "Поддержание";
    case MODE_PILOT: return "Фитиль";
    case MODE_ALARM: return "Авария";
    default: return "?";
  }
}

static void saveOne(Preferences& pr, uint8_t m){
  char key[8]; snprintf(key,sizeof(key),"p%u",m);
  pr.putBytes(key, &s_profiles[m], sizeof(ModeProfile));
}
static bool loadOne(Preferences& pr, uint8_t m){
  char key[8]; snprintf(key,sizeof(key),"p%u",m);
  size_t sz = pr.getBytesLength(key);
  if(sz!=sizeof(ModeProfile)) return false;
  pr.getBytes(key, &s_profiles[m], sizeof(ModeProfile));
  return true;
}

bool profilesLoadFromNVS(){
  Preferences pr; 
  if(!pr.begin("boiler_prof", true)) return false;
  bool ok=true;
  for(uint8_t i=0;i<6;i++){
    if(!loadOne(pr,i)){ ok=false; break; }
  }
  pr.end();
  if(!ok) logMsg("NVS: профили не найдены/битые → дефолты");
  return ok;
}

void profilesSaveToNVS(){
  Preferences pr;
  if(!pr.begin("boiler_prof", false)) return;
  for(uint8_t i=0;i<6;i++) saveOne(pr,i);
  pr.end();
  logMsg("NVS: профили сохранены");
}

void profileFactoryReset(uint8_t m){
  if(m>5)m=5;
  s_profiles[m]=s_defaults[m];
  logMsg(String("Профиль ")+m+" → заводские");
}

void profilesInit(){
  commonInit();
  // копируем дефолты в рабочий массив
  for(uint8_t i=0;i<6;i++) s_profiles[i]=s_defaults[i];
  // пробуем загрузить сохранённые
  profilesLoadFromNVS();
  applyProfileToCfg(g_boilerMode);
}

#include <Preferences.h>
CommonSettings g_common = { 800, 1500, 85.0f, {12.5,25,37.5,50,60,70,80,100,100,100}, {12.5,25,37.5,50,60,70,80,100,100,100} };
static void commonSave(Preferences& pr){
  pr.putUShort("amin_on",   g_common.aug_min_ton_ms);
  pr.putUShort("amin_off",  g_common.aug_min_toff_ms);
  pr.putFloat ("tmax",      g_common.T_supply_max);
  pr.putBytes ("fan10",     g_common.fan_steps, sizeof(g_common.fan_steps));
  pr.putBytes ("aug10",     g_common.auger_steps10, sizeof(g_common.auger_steps10));
}
static bool commonLoad(Preferences& pr){
  g_common.aug_min_ton_ms  = pr.getUShort("amin_on",  g_common.aug_min_ton_ms);
  g_common.aug_min_toff_ms = pr.getUShort("amin_off", g_common.aug_min_toff_ms);
  g_common.T_supply_max    = pr.getFloat ("tmax",     g_common.T_supply_max);
  pr.getBytes("fan10", g_common.fan_steps, sizeof(g_common.fan_steps));
  pr.getBytes("aug10", g_common.auger_steps10, sizeof(g_common.auger_steps10));
  return true;
}
void commonInit(){ Preferences pr; if(pr.begin("boiler_com", true)){ commonLoad(pr); pr.end(); } }
void commonSaveToNVS(){ Preferences pr; if(pr.begin("boiler_com", false)){ commonSave(pr); pr.end(); } }
bool commonLoadFromNVS(){ Preferences pr; bool ok=false; if(pr.begin("boiler_com", true)){ ok=commonLoad(pr); pr.end(); } return ok; }
void commonFactoryReset(){ commonSaveToNVS(); }
