// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: sensors.cpp
#include "sensors.h"
#include "pins.h"
#include "logging.h"

#include <OneWire.h>
#include <DallasTemperature.h>
#include "max6675.h"

#define SENSOR_PERIOD_MS 1000
#define SMA_N 3

static OneWire oneWire(PIN_ONEWIRE);
static DallasTemperature dallas(&oneWire);
static MAX6675 thermo(PIN_MAX6675_SCK, PIN_MAX6675_CS, PIN_MAX6675_SO);

static uint32_t lastTick=0;

static float t_ds1_raw=NAN, t_ds2_raw=NAN, t_k_raw=NAN;
static float t_ds1=NAN,     t_ds2=NAN,     t_k=NAN;
static float hist1[SMA_N]={NAN}, hist2[SMA_N]={NAN};
static uint8_t hix=0;

static float smaPush(float hist[], float x){
  if (isnan(x)) return x;
  hist[hix]=x;
  float s=0; int n=0;
  for(uint8_t i=0;i<SMA_N;i++){ if(!isnan(hist[i])){ s+=hist[i]; n++; } }
  return n? (s/n): x;
}

static float readDS(uint8_t idx, float prev){
  float v = dallas.getTempCByIndex(idx);
  if (v == DEVICE_DISCONNECTED_C || v<-55 || v>125){
    delay(30); v = dallas.getTempCByIndex(idx);
    if (v == DEVICE_DISCONNECTED_C || v<-55 || v>125){
      delay(30); v = dallas.getTempCByIndex(idx);
      if (v == DEVICE_DISCONNECTED_C || v<-55 || v>125) return prev;
    }
  }
  return v;
}

void sensorsInit(){
  dallas.begin();
}

void sensorsTick(){
  uint32_t now=millis();
  if(now-lastTick < SENSOR_PERIOD_MS) return;
  lastTick=now;

  dallas.requestTemperatures();
  float v1 = readDS(0, t_ds1_raw);
  float v2 = readDS(1, t_ds2_raw);
  t_ds1_raw=v1; t_ds2_raw=v2;
  t_ds1 = smaPush(hist1, t_ds1_raw);
  t_ds2 = smaPush(hist2, t_ds2_raw);
  hix=(hix+1)%SMA_N;

  t_k_raw = thermo.readCelsius();
  if(!isnan(t_k_raw) && t_k_raw>-200 && t_k_raw<1200) t_k=t_k_raw;
}

float getTsupply(){ return t_ds1; }
float getTreturn(){ return t_ds2; }
float getTflue()  { return t_k;   }
