// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: ui_index.cpp

#include "ui_index.h"

String makeIndexHtml(const char* FW){
  // Без «сырых» литералов: собираем строкой — так надёжнее для Arduino IDE
  String h;
  h += "<!doctype html><html lang='ru'><head><meta charset='utf-8'>";
  h += "<meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no'>";
  h += "<title>Управление котлом</title>";
  h += "<style>body{background:#0f1115;color:#e6eaf2;font:16px system-ui}";
  h += ".wrap{max-width:1040px;margin:0 auto;padding:16px}";
  h += ".card{background:#161a22;border:1px solid #1f2532;border-radius:14px;padding:14px;margin:10px 0}";
  h += ".btns{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}";
  h += "button{border:1px solid #242b3a;background:#222837;color:#fff;padding:12px;border-radius:12px;font-weight:600;cursor:pointer}";
  h += ".tabs{display:flex;gap:8px;margin:10px 0} .tab{padding:10px 14px;border-radius:12px;border:1px solid #242b3a;background:#1a1f2b;cursor:pointer}";
  h += ".tab.active{outline:2px solid #2b8cff;outline-offset:2px} .hidden{display:none}";
  h += "label{display:block;margin-bottom:6px;color:#9aa3b2} input,select{width:100%;padding:8px;border-radius:8px;border:1px solid #202638;background:#111521;color:#fff}";
  h += ".row{display:grid;grid-template-columns:200px 1fr;gap:10px;align-items:center}";
  h += "</style></head><body><div class='wrap'>";
  h += "<h1>Котёл ("; h += FW; h += ")</h1>";
  h += "<div class='tabs'><div class='tab active' data-tab='panel'>Панель</div><div class='tab' data-tab='settings'>Настройки</div></div>";
  h += "<div id='tab-panel'>";
  h += "<div class='card'><div id='temps'>Подача: <b id='t1'>—</b> °C | Обратка: <b id='t2'>—</b> °C | Дымовые: <b id='t3'>—</b> °C</div></div>";
  h += "<div class='card'><div>Скорости ПЧ</div><div class='btns'>";
  h += "<button data-speed='0'>СТОП</button>";
  const char* lbl[8] = {"12.5%","25%","37.5%","50%","60%","70%","80%","100%"};
  for(int i=0;i<8;i++){ h += String("<button data-speed='")+String(i+1)+"'>"+lbl[i]+"</button>"; }
  h += "</div></div>";
  h += "<div class='card'><div class='row'><label>Режим</label><select id='boilMode'>";
  h += "<option value='0'>Выключен</option><option value='1'>Ручной</option><option value='2'>Розжиг</option>";
  h += "<option value='3'>Нагрев</option><option value='4'>Поддержание</option><option value='5'>Остывание</option></select></div>";
  h += "<div class='row'><label>Уставка подачи, °C</label><input id='setp' type='number' min='30' max='85' step='1' value='60'></div>";
  h += "<button id='apply'>Применить</button>";
  h += "<div>Текущий режим: <b id='modeName'>—</b></div></div>";
  h += "<div class='card'><pre id='logs' style='white-space:pre-wrap;max-height:260px;overflow:auto'>—</pre><button id='btnReloadLogs'>Обновить журнал</button></div>";
  h += "</div>"; // panel

  h += "<div id='tab-settings' class='hidden'>";
  h += "<div class='card'><div class='row'><label>Режим для редактирования</label><select id='cfgMode'>";
  h += "<option value='1'>Ручной</option><option value='2'>Розжиг</option><option value='3'>Нагрев</option><option value='4'>Поддержание</option><option value='5'>Остывание</option>";
  h += "</select></div></div>";
  h += "<div class='card'><b>Температуры и регулятор</b>";
  h += "<div class='row'><label>Целевая температура</label><input id='c_T_set' type='number' step='0.5'></div>";
  h += "<div class='row'><label>Гистерезис</label><input id='c_T_hyst' type='number' step='0.1'></div>";
  h += "<div class='row'><label>Kp</label><input id='c_Kp' type='number' step='0.001'></div>";
  h += "<div class='row'><label>Ki</label><input id='c_Ki' type='number' step='0.0001'></div>";
  h += "<div class='row'><label>Дымовые — низ</label><input id='c_Tfl_low' type='number' step='1'></div>";
  h += "<div class='row'><label>Дымовые — верх</label><input id='c_Tfl_high' type='number' step='1'></div>";
  h += "</div>";
  h += "<div class='card'><b>Шнек (ступени и времена)</b>";
  for(int i=0;i<4;i++){
    h += "<div class='row'><label>Ступень "+String(i+1)+" (доля 0..1)</label><input id='c_s"+String(i)+"' type='number' step='0.01'></div>";
    h += "<div class='row'><label>Время "+String(i+1)+" (сек)</label><input id='c_ton"+String(i)+"' type='number' step='1'></div>";
  }
  h += "<div class='row'><label>Пауза мин (сек)</label><input id='c_off_min' type='number' step='1'></div>";
  h += "<div class='row'><label>Пауза макс (сек)</label><input id='c_off_max' type='number' step='1'></div>";
  h += "<div class='row'><label>Базовая пауза</label><input id='c_off_base' type='number' step='0.5'></div>";
  h += "<div class='row'><label>Чувствительность</label><input id='c_alpha' type='number' step='0.05'></div>";
  h += "<div class='row'><label>Разгон шнека (с)</label><input id='c_ramp' type='number' step='0.1'></div>";
  h += "<div class='row'><label>Запас к разгонам (с)</label><input id='c_rsafe' type='number' step='0.1'></div>";
  h += "<div class='row'><label>Розжиг (мс)</label><input id='c_ign' type='number' step='1000'></div>";
  h += "<div class='row'><label>Остывание (мс)</label><input id='c_cool' type='number' step='1000'></div>";
  h += "<button id='cfgLoad'>Загрузить профиль</button> <button id='cfgSave'>Сохранить профиль</button> <button id='cfgApplyToCurrent'>Применить</button>";
  h += "</div>";
  h += "</div>"; // settings

  // JS
  h += "<script>";
  h += "const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));";
  h += "function switchTab(t){ $$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===t)); $('#tab-panel').classList.toggle('hidden',t!=='panel'); $('#tab-settings').classList.toggle('hidden',t!=='settings'); }";
  h += "$$('.tab').forEach(x=>x.addEventListener('click',()=>switchTab(x.dataset.tab)));";
  h += "async function fetchStatus(){ try{ const r=await fetch('/api/status',{cache:'no-store'}); const j=await r.json();";
  h += "$('#t1').textContent=(j.temp&&j.temp.ds1!=null)?Number(j.temp.ds1).toFixed(1):'—';";
  h += "$('#t2').textContent=(j.temp&&j.temp.ds2!=null)?Number(j.temp.ds2).toFixed(1):'—';";
  h += "$('#t3').textContent=(j.temp&&j.temp.stack!=null)?Number(j.temp.stack).toFixed(1):'—';";
  h += "document.querySelectorAll('.btns button').forEach(b=>b.classList.toggle('active', Number(b.dataset.speed)===Number(j.speed||0)));";
  h += "$('#modeName').textContent=(j.boiler&&j.boiler.modeName)||'—'; $('#setp').value=(j.boiler&&j.boiler.setpoint)||60; }catch(e){} }";
  h += "async function sendSpeed(s){ try{ const r=await fetch('/api/cmd',{method:'POST',headers:{'Content-Type':'application/json; charset=utf-8'},body:JSON.stringify({speed:Number(s)})}); const j=await r.json(); }catch(e){ alert('ERR: '+e.message);} }";
  h += "async function applyMode(){ try{ const body={mode:Number($('#boilMode').value), setpoint:Number($('#setp').value)}; await fetch('/api/boiler',{method:'POST',headers:{'Content-Type':'application/json; charset=utf-8'},body:JSON.stringify(body)}); await fetchStatus(); }catch(e){alert('Ошибка: '+e.message);} }";
  h += "document.querySelectorAll('.btns button').forEach(b=>b.addEventListener('click',()=>sendSpeed(b.dataset.speed)));";
  h += "$('#apply').addEventListener('click', applyMode);";
  h += "$('#btnReloadLogs').addEventListener('click', async()=>{ try{ const r=await fetch('/api/logs',{cache:'no-store'}); $('#logs').textContent=await r.text(); }catch(e){ $('#logs').textContent='Ошибка: '+e.message; } });";
  h += "// Настройки профилей";
  h += "function mVal(){ return Number($('#cfgMode').value); }";
  h += "async function cfgLoad(){ const m=mVal(); const r=await fetch('/api/profile?m='+m); const c=await r.json();";
  h += "$('#c_T_set').value=c.T_set; $('#c_T_hyst').value=c.T_hyst; $('#c_Kp').value=c.Kp; $('#c_Ki').value=c.Ki; $('#c_Tfl_low').value=c.Tflue_low; $('#c_Tfl_high').value=c.Tflue_high;";
  h += "for(let i=0;i<4;i++){ $('#c_s'+i).value=c.steps[i]; $('#c_ton'+i).value=c.ton[i]; }";
  h += "$('#c_off_min').value=c.off_min; $('#c_off_max').value=c.off_max; $('#c_off_base').value=c.off_base; $('#c_alpha').value=c.alpha;";
  h += "$('#c_ramp').value=c.ramp_sec; $('#c_rsafe').value=c.ramp_safety; $('#c_ign').value=c.ign_ms; $('#c_cool').value=c.cool_ms; }";
  h += "async function cfgSave(){ const m=mVal(); const c={ T_set:Number($('#c_T_set').value), T_hyst:Number($('#c_T_hyst').value), Kp:Number($('#c_Kp').value), Ki:Number($('#c_Ki').value), Tflue_low:Number($('#c_Tfl_low').value), Tflue_high:Number($('#c_Tfl_high').value), steps:[Number($('#c_s0').value),Number($('#c_s1').value),Number($('#c_s2').value),Number($('#c_s3').value)], ton:[Number($('#c_ton0').value),Number($('#c_ton1').value),Number($('#c_ton2').value),Number($('#c_ton3').value)], off_min:Number($('#c_off_min').value), off_max:Number($('#c_off_max').value), off_base:Number($('#c_off_base').value), alpha:Number($('#c_alpha').value), ramp_sec:Number($('#c_ramp').value), ramp_safety:Number($('#c_rsafe').value), ign_ms:Number($('#c_ign').value), cool_ms:Number($('#c_cool').value)}; await fetch('/api/profile?m='+m,{method:'POST',headers:{'Content-Type':'application/json; charset=utf-8'},body:JSON.stringify(c)}); alert('Профиль сохранён'); }";
  h += "async function cfgApplyToCurrent(){ const m=mVal(); await fetch('/api/boiler',{method:'POST',headers:{'Content-Type':'application/json; charset=utf-8'},body:JSON.stringify({mode:m})}); await fetchStatus(); alert('Профиль применён'); }";
  h += "$('#cfgLoad').addEventListener('click', cfgLoad); $('#cfgSave').addEventListener('click', cfgSave); $('#cfgApplyToCurrent').addEventListener('click', cfgApplyToCurrent); $('#cfgMode').addEventListener('change', cfgLoad);";
  h += "fetchStatus(); setInterval(fetchStatus,1000); cfgLoad();";
  h += "</script></div></body></html>";
  return h;
}
