// FW-VERSION: V12.3-common-pilot (2025-10-30) — latest archive generated by ChatGPT; file: vfd.cpp
#include "vfd.h"
#include "logging.h"

volatile uint8_t g_speed_mode = 0;
uint32_t         g_lastSpeedChangeMs = 0;

static const uint8_t PRESET_BITS[8][3] = {
  /*PC-00*/ {0,0,0}, /*PC-01*/ {1,0,0}, /*PC-02*/ {0,1,0}, /*PC-03*/ {1,1,0},
  /*PC-04*/ {0,0,1}, /*PC-05*/ {1,0,1}, /*PC-06*/ {0,1,1}, /*PC-07*/ {1,1,1}
};

void setPresetBits(uint8_t idx){
  if(idx>7) idx=7;
  bool ms1 = PRESET_BITS[idx][0];
  bool ms2 = PRESET_BITS[idx][1];
  bool ms3 = PRESET_BITS[idx][2];
  setRelay(PIN_RELAY_MS1, ms1);
  setRelay(PIN_RELAY_MS2, ms2);
  setRelay(PIN_RELAY_MS3, ms3);
}

void vfdInit(){
  applySpeed(0);
}

void applySpeed(uint8_t sp){
  if(sp==0){
    setRelay(PIN_RELAY_MS1,false);
    setRelay(PIN_RELAY_MS2,false);
    setRelay(PIN_RELAY_MS3,false);
    setRelay(PIN_RELAY_RUN,false);
    g_speed_mode=0;
    g_lastSpeedChangeMs=0;
    logMsg("Скорость: СТОП");
    return;
  }
  if(sp>8) sp=8;
  uint8_t idx=sp-1;
  setRelay(PIN_RELAY_RUN,true);
  setPresetBits(idx);
  g_speed_mode=sp;
  g_lastSpeedChangeMs=millis();
  logMsg("Скорость -> PC-"+String(idx));
}
